name: Get YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
        
         j86しまなみ海道ライブカメラ／来島海峡大橋
    - name: Get j86.m3u8
      run: |
         touch ./j86.m3u8
         sudo cat >./j86.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.youtube.com/watch?v=ubX3YSoF-ys)
         EOL   
         
         j87海王丸ライブカメラ
    - name: Get j87.m3u8
      run: |
         touch ./j87.m3u8
         sudo cat >./j87.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.youtube.com/watch?v=-UsW0JsRZXM)
         EOL    
         
         j88道路カメラ_縁結び大橋
    - name: Get j88.m3u8
      run: |
         touch ./j88.m3u8
         sudo cat >./j88.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.youtube.com/watch?v=gCSr3Qm3BDM)
         EOL    
         
         j89しまなみライブカメラ【EBC】
    - name: Get j89.m3u8
      run: |
         touch ./j89.m3u8
         sudo cat >./j89.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.youtube.com/watch?v=OV0JEv6C2QQ)
         EOL    
         
         j90能登千里浜レストハウス（石川県）
    - name: Get j90.m3u8
      run: |
         touch ./j90.m3u8
         sudo cat >./j90.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.youtube.com/watch?v=GcVWo1DOeGc)
         EOL   
         
         j91【石川県羽咋市】千里浜ライブカメラ のライブ配信
    - name: Get j91.m3u8
      run: |
         touch ./j91.m3u8
         sudo cat >./j91.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.youtube.com/watch?v=kqkDQNe9EQI)
         EOL   
         
         j92サンポート高松ライブカメラ
    - name: Get j92.m3u8
      run: |
         touch ./j92.m3u8
         sudo cat >./j92.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.youtube.com/watch?v=SQkm4hLoRb0)
         EOL    
         
         j93姫路城ライブカメラ
    - name: Get j93.m3u8
      run: |
         touch ./j93.m3u8
         sudo cat >./j93.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.youtube.com/watch?v=ifEXHrCS8Oc)
         EOL    
         
         j94神戸市垂水区-明石海峡大橋
    - name: Get j94.m3u8
      run: |
         touch ./j94.m3u8
         sudo cat >./j94.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.youtube.com/watch?v=piO8TdcF2qQ)
         EOL    
         
         j95上高地河童橋ライブカメラ
    - name: Get j95.m3u8
      run: |
         touch ./j95.m3u8
         sudo cat >./j95.m3u8 <<EOL
         #EXTM3U
         #EXT-X-VERSION:3
         #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
         $(yt-dlp --print urls https://www.youtube.com/watch?v=Iv2VUE_UhRQ)
         EOL    
         
    - name: git add
      run: |
         git add -A
         ls -la
    - name: commit & push
      run: |
         git commit -m "links are updated"
         git push
